name: 📇 Submit a Speaker Profile
description: Add yourself or someone else to the Speaker Bank
title: "[Speaker] Name | Country"
labels: ["speaker-bank", "submission"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the Speaker Bank.
        Please fill in the details exactly as you would like them to appear on the website.

  - type: input
    attributes:
      label: Full name
      placeholder: e.g. Amina Said
    validations:
      required: true

  - type: input
    attributes:
      label: Country
      placeholder: e.g. Kenya
    validations:
      required: true

  - type: textarea
    attributes:
      label: Topics of Expertise
      description: List key topics separated by commas
      placeholder: e.g. AI Ethics, Youth Participation, Digital Inclusion
    validations:
      required: true

  - type: input
    attributes:
      label: Languages
      placeholder: e.g. English, Swahili
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Available For
      multiple: true
      options:
        - Panels
        - Workshops
        - Moderation
        - Trainings
        - Keynotes
        - Policy Dialogues
        - Other

  - type: input
    attributes:
      label: Link
      description: LinkedIn, personal website, or professional profile
      placeholder: https://www.linkedin.com/in/username
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Consent
      options:
        - label: I confirm that this information can be published on the Speaker Bank website
          required: true
