name: 📝 Submit a New Opportunity
description: Suggest a new conference, fellowship, job, or opportunity
title: "🆕 New Opportunity: "
labels: ["new opportunity"]
assignees: []

body:
  - type: input
    attributes:
      label: Program or Event Name
      placeholder: e.g. ICANN Fellowship
    validations:
      required: true

  - type: input
    attributes:
      label: Link to Opportunity
      placeholder: https://example.com
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Type of Opportunity
      options:
        - Conference
        - Fellowship
        - Mentorship
        - Job / Internship
        - Funding
        - Training
    validations:
      required: true

  - type: input
    attributes:
      label: Region
      placeholder: Global, Africa, Europe (optional)

  - type: input
    attributes:
      label: Application Deadline
      placeholder: e.g. 15 September 2026 (optional)

  - type: textarea
    attributes:
      label: Additional Information
      placeholder: Any context, eligibility notes, or comments
