name: 🌟 Submit a Success Story
description: Share a real-world Internet Governance success story
title: "[Success Story] Short descriptive title"
labels: ["success-story", "submission"]

body:
  - type: input
    attributes:
      label: Story title
    validations:
      required: true

  - type: input
    attributes:
      label: Author(s) / Organization
    validations:
      required: true

  - type: input
    attributes:
      label: Country / Region
    validations:
      required: true

  - type: textarea
    attributes:
      label: Story description
    validations:
      required: true

  - type: textarea
    attributes:
      label: Impact and outcomes
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Consent
      options:
        - label: I confirm this story can be published
          required: true
